repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: [ --fix, --fix-only, --config=pyproject.toml ]
    -   id: ruff-format
        args: [ --config=pyproject.toml ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            "types-requests",
            "pydantic",
            "typer[all]",
            "rich"
        ]