repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
    -   id: ruff
        args: [ --fix ]
        stages: [ 'pre-commit' ]
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: ty
        name: ty
        entry: bash -c 'cd packages/prime && uv run ty check src/'
        language: system
        files: ^packages/prime/.*\.py$
        pass_filenames: false