[project]
name = "prime-cli"
version = "0.1.0"
description = "Prime Intellect CLI"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Prime Intellect", email = "contact@primeintellect.ai" }
]
dependencies = [
    "typer[all]>=0.9.0",
    "requests>=2.31.0",
    "rich>=13.3.1",  
    "pydantic>=2.0.0" 
]

[project.scripts]
prime = "prime_cli.main:run"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=22.3.0",    # Code formatting
    "isort>=5.10.1",    # Import sorting
    "ruff>=0.1.8",      # Fast linter
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.ruff]
line-length = 88
target-version = "py38"