[project]
name = "prime-core"
version = "0.1.1"
description = "Prime Intellect Core - Shared HTTP client and configuration (internal package)"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.25.0",
    "pydantic>=2.0.0",
]
classifiers = [
    "Private :: Do Not Upload",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/prime_core"]
